export const brandImages = [
    [
        "https://cdn.shopify.com/s/files/1/1473/3902/files/1_2d2e4da3-b76c-4757-8de7-6d2e345c5d9f.jpg?v=1685407358", 
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_3503b6ff-48f6-42be-a7cd-8e5049a15ea7.jpg?v=1678780368",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_66b4db7d-a8ac-46b7-8686-aff540843f89.jpg?v=1677486850",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_ba6c1fe1-bc5b-474e-a729-f79e1c1b4489.jpg?v=1673254274",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_42198621-697d-40a3-9d16-3026f7479610.jpg?v=1652148845",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_7144fd56-6aa7-4714-9511-cb7886704445.jpg?v=1652148308",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_78690d0c-53ee-4b7e-876e-e51fe57ca2aa.jpg?v=1652147867",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_29738ab6-6492-4185-8529-05fd4d09e26c.jpg?v=1652145420"
    ], 
    [
        "https://cdn.shopify.com/s/files/1/1473/3902/files/1_40f16107-1670-45b2-b32f-c2891f500081.jpg?v=1685940229",
        "https://cdn.shopify.com/s/files/1/1473/3902/files/1_ef3fe437-391c-483d-8637-ca9e34c9507f.jpg?v=1685781160",
        "https://cdn.shopify.com/s/files/1/1473/3902/files/1_ec4ec3fa-1212-4d63-a763-8de69f979054.jpg?v=1685686460",
        "https://cdn.shopify.com/s/files/1/1473/3902/files/1_00425f2c-b450-45f4-a741-2cf1d76059a9.jpg?v=1685608911",
        "https://cdn.shopify.com/s/files/1/1473/3902/files/1_02800de1-84c1-407f-be68-b19e6cc2988b.jpg?v=1685428666",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_26463b7c-7a99-4c84-bb03-83d420625cae.jpg?v=1646033760",
    ], 
    [
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_5baca162-14b4-4508-9c21-36eb1b478153.jpg?v=1652660968",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_3a3097be-a552-44ce-9537-5a0f1074fb42.jpg?v=1605859490",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_d35f64ae-625b-45de-b8bb-55dbf132eaf7.jpg?v=1653556327",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/3_74665e23-f096-4a67-aadd-6a19e7d4e323.jpg?v=1644994865"
    ], 
    [
        "https://cdn.shopify.com/s/files/1/1473/3902/products/2_16ffcb1e-bf66-4459-a709-4ffaca7d44aa.jpg?v=1648615873",
        "https://zealpc.net/cdn/shop/products/Pearlio60g_2048x.jpg?v=1640493778",
        "https://zealpc.net/cdn/shop/products/CrystalTactileSwitch_2048x.jpg?v=1640490153",
        "https://zealpc.net/cdn/shop/products/Clickiez60g_2048x.jpg?v=1640482842"
    ], 
    [
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_468db451-28fb-496f-a2ea-f04bdc2ae26d.jpg?v=1668057312",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_2c6f15de-6510-4679-ac52-86375e0fe11f.jpg?v=1650607772",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_6e2d5339-eb22-4ef8-bead-60f81f78ce8b.jpg?v=1614072983",
        "https://cdn.shopify.com/s/files/1/1473/3902/products/1_d581eb7f-a7e6-43ec-9ecb-3fbd4e04276d.jpg?v=1646015875"
    ], 
    [
        "https://i.imgur.com/Nq45FJD.png",
        "https://i.imgur.com/lQOspQB.png",
        "https://i.imgur.com/TgeuwHx.png",
        "https://i.imgur.com/TX22SsK.png"
    ]
]

export const switchData = [
    {
        "Brand": "Cherry",
        "Name": "MX Blue",
        "CompleteName": "Cherry MX Blue",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Black",
        "CompleteName": "Cherry MX Black",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Brown",
        "CompleteName": "Cherry MX Brown",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Red",
        "CompleteName": "Cherry MX Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Clear",
        "CompleteName": "Cherry MX Clear",
        "Type": "Tactile",
        "ActuationForce": 65,
        "ActuationDistance": 2,
        "BottomOutForce": 95,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Green",
        "CompleteName": "Cherry MX Green",
        "Type": "Clicky",
        "ActuationForce": 70,
        "ActuationDistance": 2,
        "BottomOutForce": 90,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX White",
        "CompleteName": "Cherry MX White",
        "Type": "Clicky",
        "ActuationForce": 80,
        "ActuationDistance": 2.2,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Tactile Grey",
        "CompleteName": "Cherry MX Tactile Grey",
        "Type": "Tactile",
        "ActuationForce": 80,
        "ActuationDistance": 2,
        "BottomOutForce": 110,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Linear Grey",
        "CompleteName": "Cherry MX Linear Grey",
        "Type": "Linear",
        "ActuationForce": 80,
        "ActuationDistance": 2,
        "BottomOutForce": 115,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Silent Black",
        "CompleteName": "Cherry MX Silent Black",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 1.9,
        "BottomOutForce": 80,
        "TravelDistance": 3.7,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Silver",
        "CompleteName": "Cherry MX Silver",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.2,
        "BottomOutForce": 60,
        "TravelDistance": 3.4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Speed Silver",
        "CompleteName": "Cherry MX Speed Silver",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.2,
        "BottomOutForce": 65,
        "TravelDistance": 3.4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Silent Red",
        "CompleteName": "Cherry MX Silent Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.9,
        "BottomOutForce": 60,
        "TravelDistance": 3.7,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Nature White",
        "CompleteName": "Cherry MX Nature White",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 65,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Low Profile Red",
        "CompleteName": "Cherry MX Low Profile Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.2,
        "BottomOutForce": 80,
        "TravelDistance": 3.2,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Name": "MX Low Profile Speed",
        "CompleteName": "Cherry MX Low Profile Speed",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1,
        "BottomOutForce": 80,
        "TravelDistance": 3.2,
        "StemType": "",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Name": "Romer-G Tactile",
        "CompleteName": "Logitech Romer-G Tactile",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 1.5,
        "BottomOutForce": 55,
        "TravelDistance": 3,
        "StemType": "Romer-G",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Name": "Romer-G Linear",
        "CompleteName": "Logitech Romer-G Linear",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.5,
        "BottomOutForce": 55,
        "TravelDistance": 3.2,
        "StemType": "Romer-G",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Name": "GX Blue",
        "CompleteName": "Logitech GX Blue",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 3.7,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Name": "GX Brown",
        "CompleteName": "Logitech GX Brown",
        "Type": "Tactile",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Name": "GX Red",
        "CompleteName": "Logitech GX Red",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 1.9,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Chery",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Razer",
        "Name": "Green",
        "CompleteName": "Razer Green",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Razer",
        "Name": "Orange",
        "CompleteName": "Razer Orange",
        "Type": "Tactile",
        "ActuationForce": 40,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Razer",
        "Name": "Yellow",
        "CompleteName": "Razer Yellow",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.2,
        "BottomOutForce": 45,
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Razer",
        "Name": "Clicky Optical Switch",
        "CompleteName": "Razer Clicky Optical Switch",
        "Type": "Clicky",
        "ActuationForce": 45,
        "ActuationDistance": 1.5,
        "BottomOutForce": 70,
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Optical switch"
    },
    {
        "Brand": "Razer",
        "Name": "Linear Optical Switch",
        "CompleteName": "Razer Linear Optical Switch",
        "Type": "Linear",
        "ActuationForce": 40,
        "ActuationDistance": 1,
        "BottomOutForce": 60,
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Steelseries",
        "Name": "QS1",
        "CompleteName": "Steelseries QS1",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.5,
        "BottomOutForce": 45,
        "TravelDistance": 3.5,
        "StemType": "QS1",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Coolermaster",
        "Name": "Hybrid capacitive",
        "CompleteName": "Coolermaster Hybrid capacitive",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 1,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": "Topre switches"
    },
    {
        "Brand": "Roccat",
        "Name": "Titan",
        "CompleteName": "Roccat Titan",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 1.8,
        "BottomOutForce": "",
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": "Only on Roccat boards, force curves to come!"
    },
    {
        "Brand": "IBM",
        "Name": "Buckling Spring",
        "CompleteName": "IBM Buckling Spring",
        "Type": "Clicky",
        "ActuationForce": 70,
        "ActuationDistance": 2,
        "BottomOutForce": 90,
        "TravelDistance": 4,
        "StemType": "Buckling Spring",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Topre",
        "Name": 30,
        "CompleteName": "Topre 30",
        "Type": "Tactile",
        "ActuationForce": 30,
        "ActuationDistance": 2,
        "BottomOutForce": 70,
        "TravelDistance": 4,
        "StemType": "Topre",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Topre",
        "Name": 35,
        "CompleteName": "Topre 35",
        "Type": "Tactile",
        "ActuationForce": 25,
        "ActuationDistance": 2,
        "BottomOutForce": 50,
        "TravelDistance": 4,
        "StemType": "Topre",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Topre",
        "Name": 45,
        "CompleteName": "Topre 45",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Topre",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Topre",
        "Name": 55,
        "CompleteName": "Topre 55",
        "Type": "Tactile",
        "ActuationForce": 65,
        "ActuationDistance": 2,
        "BottomOutForce": 110,
        "TravelDistance": 4,
        "StemType": "Topre",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Matias",
        "Name": "Quiet Click",
        "CompleteName": "Matias Quiet Click",
        "Type": "Tactile",
        "ActuationForce": 50,
        "ActuationDistance": 2.2,
        "BottomOutForce": 35,
        "TravelDistance": 3.5,
        "StemType": "ALPS",
        "PrebuiltAvailability": "",
        "Notes": "SKCM/ALPS clones"
    },
    {
        "Brand": "Matias",
        "Name": "Click",
        "CompleteName": "Matias Click",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 2.2,
        "BottomOutForce": 35,
        "TravelDistance": 3.5,
        "StemType": "ALPS",
        "PrebuiltAvailability": "",
        "Notes": "SKCM/ALPS clones"
    },
    {
        "Brand": "Matias",
        "Name": "Quiet Linear",
        "CompleteName": "Matias Quiet Linear",
        "Type": "Linear",
        "ActuationForce": 35,
        "ActuationDistance": 2.2,
        "BottomOutForce": 35,
        "TravelDistance": 3.5,
        "StemType": "ALPS",
        "PrebuiltAvailability": "",
        "Notes": "SKCM/ALPS clones"
    },
    {
        "Brand": "Gateron",
        "Name": "Clear",
        "CompleteName": "Gateron Clear",
        "Type": "Linear",
        "ActuationForce": 35,
        "ActuationDistance": 2.2,
        "BottomOutForce": 35,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Not similar to Cherry Clears at all"
    },
    {
        "Brand": "Gateron",
        "Name": "Red",
        "CompleteName": "Gateron Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2.2,
        "BottomOutForce": 55,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Name": "Yellow",
        "CompleteName": "Gateron Yellow",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Name": "Black",
        "CompleteName": "Gateron Black",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": 75,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Name": "Brown",
        "CompleteName": "Gateron Brown",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 2.65,
        "BottomOutForce": 50,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Name": "Blue",
        "CompleteName": "Gateron Blue",
        "Type": "Clicky",
        "ActuationForce": 55,
        "ActuationDistance": 2.2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Name": "Green",
        "CompleteName": "Gateron Green",
        "Type": "Clicky",
        "ActuationForce": 80,
        "ActuationDistance": 2.2,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Name": "Ink",
        "CompleteName": "Gateron Ink",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 2.2,
        "BottomOutForce": 70,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Name": "Robin 62G",
        "CompleteName": "Gateron Robin 62G",
        "Type": "Linear",
        "ActuationForce": 40,
        "ActuationDistance": 2,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Red",
        "CompleteName": "Kailh Red",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 65,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Brown",
        "CompleteName": "Kailh Brown",
        "Type": "Tactile",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Black",
        "CompleteName": "Kailh Black",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Blue",
        "CompleteName": "Kailh Blue",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Speed Silver",
        "CompleteName": "Kailh Speed Silver",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 1.1,
        "BottomOutForce": 70,
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Speed Copper",
        "CompleteName": "Kailh Speed Copper",
        "Type": "Tactile",
        "ActuationForce": 50,
        "ActuationDistance": 1.1,
        "BottomOutForce": 60,
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Speed Bronze",
        "CompleteName": "Kailh Speed Bronze",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 1.1,
        "BottomOutForce": 65,
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Speed Pink",
        "CompleteName": "Kailh Speed Pink",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 1.1,
        "BottomOutForce": "",
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Speed Gold",
        "CompleteName": "Kailh Speed Gold",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 1.4,
        "BottomOutForce": 60,
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Red",
        "CompleteName": "Kailh Box Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.8,
        "BottomOutForce": 60,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Black",
        "CompleteName": "Kailh Box Black",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 1.8,
        "BottomOutForce": 75,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Navy",
        "CompleteName": "Kailh Box Navy",
        "Type": "Clicky",
        "ActuationForce": 60,
        "ActuationDistance": 1.8,
        "BottomOutForce": 90,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Jade",
        "CompleteName": "Kailh Box Jade",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 1.8,
        "BottomOutForce": 60,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Brown",
        "CompleteName": "Kailh Box Brown",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 1.8,
        "BottomOutForce": 60,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box White",
        "CompleteName": "Kailh Box White",
        "Type": "Clicky",
        "ActuationForce": 45,
        "ActuationDistance": 1.8,
        "BottomOutForce": 55,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Dark Yellow",
        "CompleteName": "Kailh Box Dark Yellow",
        "Type": "Linear",
        "ActuationForce": 70,
        "ActuationDistance": 1.8,
        "BottomOutForce": 80,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Pink",
        "CompleteName": "Kailh Box Pink",
        "Type": "Clicky",
        "ActuationForce": 65,
        "ActuationDistance": 1.8,
        "BottomOutForce": 55,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Chinese Red",
        "CompleteName": "Kailh Box Chinese Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.8,
        "BottomOutForce": 55,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Noble Yellow",
        "CompleteName": "Kailh Box Noble Yellow",
        "Type": "Clicky",
        "ActuationForce": 65,
        "ActuationDistance": 1.8,
        "BottomOutForce": 50,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Glazed Green",
        "CompleteName": "Kailh Box Glazed Green",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 1.8,
        "BottomOutForce": 50,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Ancient Grey",
        "CompleteName": "Kailh Ancient Grey",
        "Type": "Linear",
        "ActuationForce": 95,
        "ActuationDistance": 1.8,
        "BottomOutForce": 100,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Heavy Burnt Orange",
        "CompleteName": "Kailh Heavy Burnt Orange",
        "Type": "Tactile",
        "ActuationForce": 60,
        "ActuationDistance": 1.8,
        "BottomOutForce": 80,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Royal",
        "CompleteName": "Kailh Box Royal",
        "Type": "Tactile",
        "ActuationForce": 40,
        "ActuationDistance": 1.8,
        "BottomOutForce": 70,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Pale Blue",
        "CompleteName": "Kailh Box Pale Blue",
        "Type": "Clicky",
        "ActuationForce": 60,
        "ActuationDistance": 1.8,
        "BottomOutForce": 80,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Pro Burgundy",
        "CompleteName": "Kailh Pro Burgundy",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 1.7,
        "BottomOutForce": 70,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Pro Purple",
        "CompleteName": "Kailh Pro Purple",
        "Type": "Tactile",
        "ActuationForce": 50,
        "ActuationDistance": 1.7,
        "BottomOutForce": 70,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Pro Light Green",
        "CompleteName": "Kailh Pro Light Green",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 1.7,
        "BottomOutForce": 60,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Low Profile Choc Dark Yellow",
        "CompleteName": "Kailh Low Profile Choc Dark Yellow",
        "Type": "Linear",
        "ActuationForce": 70,
        "ActuationDistance": 1.5,
        "BottomOutForce": 85,
        "TravelDistance": 3,
        "StemType": "Kailh Low Profile",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Low Profile Choc Burnt Orange",
        "CompleteName": "Kailh Low Profile Choc Burnt Orange",
        "Type": "Tactile",
        "ActuationForce": 70,
        "ActuationDistance": 1.5,
        "BottomOutForce": 85,
        "TravelDistance": 3,
        "StemType": "Kailh Low Profile",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Low Profile Choc Pale Blue",
        "CompleteName": "Kailh Low Profile Choc Pale Blue",
        "Type": "Clciky",
        "ActuationForce": 70,
        "ActuationDistance": 1.5,
        "BottomOutForce": 85,
        "TravelDistance": 3,
        "StemType": "Kailh Low Profile",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Low Profile Choc Red",
        "CompleteName": "Kailh Low Profile Choc Red",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 1.5,
        "BottomOutForce": 65,
        "TravelDistance": 3,
        "StemType": "Kailh Low Profile",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Low Profile Choc Brown",
        "CompleteName": "Kailh Low Profile Choc Brown",
        "Type": "Tactile",
        "ActuationForce": 50,
        "ActuationDistance": 1.5,
        "BottomOutForce": 65,
        "TravelDistance": 3,
        "StemType": "Kailh Low Profile",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Low Profile Choc White",
        "CompleteName": "Kailh Low Profile Choc White",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 1.5,
        "BottomOutForce": 65,
        "TravelDistance": 3,
        "StemType": "Kailh Low Profile",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Low Profile Choc Navy",
        "CompleteName": "Kailh Low Profile Choc Navy",
        "Type": "Clicky",
        "ActuationForce": 60,
        "ActuationDistance": 1.5,
        "BottomOutForce": 85,
        "TravelDistance": 3,
        "StemType": "Kailh Low Profile",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Low Profile Choc Jade",
        "CompleteName": "Kailh Low Profile Choc Jade",
        "Type": "Clicky",
        "ActuationForce": 60,
        "ActuationDistance": 1.5,
        "BottomOutForce": 75,
        "TravelDistance": 3,
        "StemType": "Kailh Low Profile",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Box Red Pro",
        "CompleteName": "Kailh Box Red Pro",
        "Type": "Linear",
        "ActuationForce": 35,
        "ActuationDistance": 1.8,
        "BottomOutForce": 45,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Name": "Speed Navy",
        "CompleteName": "Kailh Speed Navy",
        "Type": "Tactile",
        "ActuationForce": 65,
        "ActuationDistance": 1.4,
        "BottomOutForce": "",
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Name": "Zealios 62 g",
        "CompleteName": "ZealPC Zealios 62 g",
        "Type": "Tactile",
        "ActuationForce": 20,
        "ActuationDistance": 2.4,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Name": "Zealios 65 g",
        "CompleteName": "ZealPC Zealios 65 g",
        "Type": "Tactile",
        "ActuationForce": 25,
        "ActuationDistance": 2.4,
        "BottomOutForce": 65,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Name": "Zealios 67 g",
        "CompleteName": "ZealPC Zealios 67 g",
        "Type": "Tactile",
        "ActuationForce": 30,
        "ActuationDistance": 2.4,
        "BottomOutForce": 67,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Name": "Zealios 78 g",
        "CompleteName": "ZealPC Zealios 78 g",
        "Type": "Tactile",
        "ActuationForce": 40,
        "ActuationDistance": 2.4,
        "BottomOutForce": 78,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Lighter Cherry MX Clear, Smoother"
    },
    {
        "Brand": "ZealPC",
        "Name": "Tiffany Blue Tealios",
        "CompleteName": "ZealPC Tiffany Blue Tealios",
        "Type": "Linear",
        "ActuationForce": "",
        "ActuationDistance": 2.4,
        "BottomOutForce": 67,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Name": "Orange Healios",
        "CompleteName": "ZealPC Orange Healios",
        "Type": "Linear",
        "ActuationForce": "",
        "ActuationDistance": 4,
        "BottomOutForce": 67,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Name": "Zilents 62 g",
        "CompleteName": "ZealPC Zilents 62 g",
        "Type": "Tactile",
        "ActuationForce": 20,
        "ActuationDistance": 2.4,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Silent Zealios"
    },
    {
        "Brand": "ZealPC",
        "Name": "Zilents 65 g",
        "CompleteName": "ZealPC Zilents 65 g",
        "Type": "Tactile",
        "ActuationForce": 25,
        "ActuationDistance": 2.4,
        "BottomOutForce": 65,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Silent Zealios"
    },
    {
        "Brand": "ZealPC",
        "Name": "Zilents 67 g",
        "CompleteName": "ZealPC Zilents 67 g",
        "Type": "Tactile",
        "ActuationForce": 30,
        "ActuationDistance": 2.4,
        "BottomOutForce": 67,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Silent Zealios"
    },
    {
        "Brand": "ZealPC",
        "Name": "Zilents 78 g",
        "CompleteName": "ZealPC Zilents 78 g",
        "Type": "Tactile",
        "ActuationForce": 40,
        "ActuationDistance": 2.4,
        "BottomOutForce": 78,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Silent Zealios"
    },
    {
        "Brand": "Input Club",
        "Name": "Hako True",
        "CompleteName": "Input Club Hako True",
        "Type": "Tactile",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": 95,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Name": "Hako Clear",
        "CompleteName": "Input Club Hako Clear",
        "Type": "Tactile",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 75,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Name": "Hako Violet",
        "CompleteName": "Input Club Hako Violet",
        "Type": "Tactile",
        "ActuationForce": 40,
        "ActuationDistance": 2,
        "BottomOutForce": 50,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Name": "Hako Royal True",
        "CompleteName": "Input Club Hako Royal True",
        "Type": "Tactile",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": 85,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Name": "Hako Royal Clear",
        "CompleteName": "Input Club Hako Royal Clear",
        "Type": "Tactile",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 85,
        "TravelDistance": 3.6,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Name": "Halo Clear",
        "CompleteName": "Input Club Halo Clear",
        "Type": "Tactile",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Name": "Halo True",
        "CompleteName": "Input Club Halo True",
        "Type": "Tactile",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 100,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Name": "MOD-L",
        "CompleteName": "MOD MOD-L",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Name": "MOD-L",
        "CompleteName": "MOD MOD-L",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Name": "MOD-M",
        "CompleteName": "MOD MOD-M",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Name": "MOD-M",
        "CompleteName": "MOD MOD-M",
        "Type": "Tactile",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 66,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Name": "MOD-H",
        "CompleteName": "MOD MOD-H",
        "Type": "Linear",
        "ActuationForce": 62,
        "ActuationDistance": 2,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Name": "MOD-H",
        "CompleteName": "MOD MOD-H",
        "Type": "Tactile",
        "ActuationForce": 62,
        "ActuationDistance": 2,
        "BottomOutForce": 78,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Name": "MOD-SH",
        "CompleteName": "MOD MOD-SH",
        "Type": "Tactile",
        "ActuationForce": 70,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Aliaz",
        "Name": "60g",
        "CompleteName": "Aliaz 60g",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Kind of similar to Zealio"
    },
    {
        "Brand": "Aliaz",
        "Name": "70g",
        "CompleteName": "Aliaz 70g",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 70,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Kind of similar to Zealio"
    },
    {
        "Brand": "Aliaz",
        "Name": "80g",
        "CompleteName": "Aliaz 80g",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Kind of similar to Zealio"
    },
    {
        "Brand": "Aliaz",
        "Name": "100g",
        "CompleteName": "Aliaz 100g",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 100,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": "Kind of similar to Zealio"
    },
    {
        "Brand": "Outemu",
        "Name": "Brown",
        "CompleteName": "Outemu Brown",
        "Type": "Tactile",
        "ActuationForce": 40,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "Blue",
        "CompleteName": "Outemu Blue",
        "Type": "Clicky",
        "ActuationForce": 46,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "Red",
        "CompleteName": "Outemu Red",
        "Type": "Linear",
        "ActuationForce": 47,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "Black",
        "CompleteName": "Outemu Black",
        "Type": "Linear",
        "ActuationForce": 65,
        "ActuationDistance": 2,
        "BottomOutForce": 84,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "Ice Silver",
        "CompleteName": "Outemu Ice Silver",
        "Type": "Linear",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 68,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "ICE Light Purple",
        "CompleteName": "Outemu ICE Light Purple",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "ICE Dustproof Brown",
        "CompleteName": "Outemu ICE Dustproof Brown",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "ICE Dark Purple",
        "CompleteName": "Outemu ICE Dark Purple",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 68,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "ICE Grey",
        "CompleteName": "Outemu ICE Grey",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 75,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "ICE Blue",
        "CompleteName": "Outemu ICE Blue",
        "Type": "Clicky",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "ICE Teal",
        "CompleteName": "Outemu ICE Teal",
        "Type": "Clicky",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 68,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "ICE Click",
        "CompleteName": "Outemu ICE Click",
        "Type": "Clicky",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 75,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "Low Profile Red",
        "CompleteName": "Outemu Low Profile Red",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 1.3,
        "BottomOutForce": "",
        "TravelDistance": 3,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "Low Profile Blue",
        "CompleteName": "Outemu Low Profile Blue",
        "Type": "Clicky",
        "ActuationForce": 60,
        "ActuationDistance": 1.3,
        "BottomOutForce": "",
        "TravelDistance": 3,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "Low Profile Black",
        "CompleteName": "Outemu Low Profile Black",
        "Type": "Linear",
        "ActuationForce": 65,
        "ActuationDistance": 1.3,
        "BottomOutForce": "",
        "TravelDistance": 3,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Name": "Low Profile Brown",
        "CompleteName": "Outemu Low Profile Brown",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 1.3,
        "BottomOutForce": "",
        "TravelDistance": 3,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Greetech",
        "Name": "Brown",
        "CompleteName": "Greetech Brown",
        "Type": "Tactile",
        "ActuationForce": 40,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Greetech",
        "Name": "Blue",
        "CompleteName": "Greetech Blue",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Greetech",
        "Name": "Red",
        "CompleteName": "Greetech Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 55,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Greetech",
        "Name": "Black",
        "CompleteName": "Greetech Black",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Tesoro",
        "Name": "Agile Red",
        "CompleteName": "Tesoro Agile Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 1.5,
        "BottomOutForce": "",
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Tesoro",
        "Name": "Agile Blue",
        "CompleteName": "Tesoro Agile Blue",
        "Type": "Clicky",
        "ActuationForce": 45,
        "ActuationDistance": 1.5,
        "BottomOutForce": "",
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Tesoro",
        "Name": "Slim Blue",
        "CompleteName": "Tesoro Slim Blue",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 1,
        "BottomOutForce": "",
        "TravelDistance": 3,
        "StemType": "Tesoro",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Tesoro",
        "Name": "Slim Blue",
        "CompleteName": "Tesoro Slim Blue",
        "Type": "",
        "ActuationForce": 45,
        "ActuationDistance": 1,
        "BottomOutForce": "",
        "TravelDistance": 3,
        "StemType": "Tesoro",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Name": "Cream",
        "CompleteName": "NovelKeys Cream",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 70,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Name": "Silk Red",
        "CompleteName": "NovelKeys Silk Red",
        "Type": "Linear",
        "ActuationForce": 35,
        "ActuationDistance": 2,
        "BottomOutForce": 55,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Name": "Silk Yellow",
        "CompleteName": "NovelKeys Silk Yellow",
        "Type": "Linear",
        "ActuationForce": 43,
        "ActuationDistance": 2,
        "BottomOutForce": 63.5,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Name": "Silk Black",
        "CompleteName": "NovelKeys Silk Black",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 72,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Name": "Silk Olivia",
        "CompleteName": "NovelKeys Silk Olivia",
        "Type": "Linear",
        "ActuationForce": 43,
        "ActuationDistance": 2,
        "BottomOutForce": 63.5,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Geekmaker",
        "Name": "Creamy Yellow",
        "CompleteName": "Geekmaker Creamy Yellow",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": "",
        "BottomOutForce": "",
        "TravelDistance": "",
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Geekmaker",
        "Name": "Creamy Pink",
        "CompleteName": "Geekmaker Creamy Pink",
        "Type": "Linear",
        "ActuationForce": 62,
        "ActuationDistance": "",
        "BottomOutForce": "",
        "TravelDistance": "",
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Geekmaker",
        "Name": "Creamy Purple",
        "CompleteName": "Geekmaker Creamy Purple",
        "Type": "Linear",
        "ActuationForce": 67,
        "ActuationDistance": "",
        "BottomOutForce": "",
        "TravelDistance": "",
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Geekmaker",
        "Name": "Creamy Green",
        "CompleteName": "Geekmaker Creamy Green",
        "Type": "Linear",
        "ActuationForce": 78,
        "ActuationDistance": "",
        "BottomOutForce": "",
        "TravelDistance": "",
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Orange Black",
        "CompleteName": "TTC Orange Black",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Orange Red",
        "CompleteName": "TTC Orange Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Orange Blue",
        "CompleteName": "TTC Orange Blue",
        "Type": "Clicky",
        "ActuationForce": 60,
        "ActuationDistance": 2.2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Orange Brown",
        "CompleteName": "TTC Orange Brown",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "YOK",
        "Name": "Red Pandas",
        "CompleteName": "YOK Red Pandas",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": "",
        "BottomOutForce": 60,
        "TravelDistance": "",
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "YOK",
        "Name": "Trash Panda",
        "CompleteName": "YOK Trash Panda",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "YOK",
        "Name": "Purple Trash Panda",
        "CompleteName": "YOK Purple Trash Panda",
        "Type": "Tactile",
        "ActuationForce": 57,
        "ActuationDistance": 2,
        "BottomOutForce": 70,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Silent Red",
        "CompleteName": "TTC Silent Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 55,
        "TravelDistance": 3.8,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Silent Brown",
        "CompleteName": "TTC Silent Brown",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 3.8,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Gold Brown",
        "CompleteName": "TTC Gold Brown",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Gold Pink",
        "CompleteName": "TTC Gold Pink",
        "Type": "",
        "ActuationForce": 37,
        "ActuationDistance": 2,
        "BottomOutForce": 45,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Wild 42g",
        "CompleteName": "TTC Wild 42g",
        "Type": "Linear",
        "ActuationForce": 42,
        "ActuationDistance": 2,
        "BottomOutForce": 52,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Wild 55g",
        "CompleteName": "TTC Wild 55g",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 68,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Varmilo",
        "Name": "EC Sakura",
        "CompleteName": "Varmilo EC Sakura",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 60,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Varmilo",
        "Name": "EC Rosery",
        "CompleteName": "Varmilo EC Rosery",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 75,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Varmilo",
        "Name": "EC Ivy",
        "CompleteName": "Varmilo EC Ivy",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 2.3,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "KBT",
        "Name": "Blue",
        "CompleteName": "KBT Blue",
        "Type": "Clicky",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "KBT",
        "Name": "Brown",
        "CompleteName": "KBT Brown",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "KBT",
        "Name": "Red",
        "CompleteName": "KBT Red",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "KBT",
        "Name": "Black",
        "CompleteName": "KBT Black",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Hall Effect",
        "Name": "Linear",
        "CompleteName": "Hall Effect Linear",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": "0.1-3.8",
        "BottomOutForce": 65,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Hall Effect",
        "Name": "Clicky",
        "CompleteName": "Hall Effect Clicky",
        "Type": "Clicky",
        "ActuationForce": 60,
        "ActuationDistance": "0.1-3.8",
        "BottomOutForce": 65,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Hall Effect",
        "Name": "Tactile",
        "CompleteName": "Hall Effect Tactile",
        "Type": "Tactile",
        "ActuationForce": 60,
        "ActuationDistance": "0.1-3.8",
        "BottomOutForce": 65,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Flaretech",
        "Name": "Red",
        "CompleteName": "Flaretech Red",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": "1.5-3.6",
        "BottomOutForce": 55,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Flaretech",
        "Name": "Black",
        "CompleteName": "Flaretech Black",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": "1.5-3.6",
        "BottomOutForce": 55,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Flaretech",
        "Name": "Blue",
        "CompleteName": "Flaretech Blue",
        "Type": "Clicky",
        "ActuationForce": 80,
        "ActuationDistance": "1.5-3.6",
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "HyperX",
        "Name": "Red",
        "CompleteName": "HyperX Red",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": "",
        "BottomOutForce": "",
        "TravelDistance": 3.8,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "HyperX",
        "Name": "Aqua",
        "CompleteName": "HyperX Aqua",
        "Type": "Tactile",
        "ActuationForce": 45,
        "ActuationDistance": "",
        "BottomOutForce": "",
        "TravelDistance": 3.8,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "c3",
        "Name": "Tangerine",
        "CompleteName": "c3 Tangerine",
        "Type": "Linear",
        "ActuationForce": 62,
        "ActuationDistance": "",
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "",
        "Name": "H1s",
        "CompleteName": "H1s",
        "Type": "Linear",
        "ActuationForce": "",
        "ActuationDistance": "",
        "BottomOutForce": 78,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Name": "Gold Pink",
        "CompleteName": "TTC Gold Pink",
        "Type": "Linear",
        "ActuationForce": 37,
        "ActuationDistance": 2,
        "BottomOutForce": 45,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys x Kailh",
        "Name": "Blueberry",
        "CompleteName": "NovelKeys x Kailh Blueberry",
        "Type": "Tactile",
        "ActuationForce": 55,
        "ActuationDistance": 3,
        "BottomOutForce": 80,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Drop",
        "Name": "Holy Panda",
        "CompleteName": "Drop Holy Panda",
        "Type": "Tactile",
        "ActuationForce": 44,
        "ActuationDistance": 2.4,
        "BottomOutForce": 62,
        "TravelDistance": 3.8,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Drop",
        "Name": "Holy Panda X",
        "CompleteName": "Drop Holy Panda X",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2.4,
        "BottomOutForce": 62,
        "TravelDistance": 3.5,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Glorious",
        "Name": "Panda",
        "CompleteName": "Glorious Panda",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 2,
        "BottomOutForce": 67,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Crystal Violet",
        "CompleteName": "Everglide Crystal Violet",
        "Type": "Tactile",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 63.5,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Sakura Pink",
        "CompleteName": "Everglide Sakura Pink",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Jade Green",
        "CompleteName": "Everglide Jade Green",
        "Type": "Tactile",
        "ActuationForce": 58,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Coral Red",
        "CompleteName": "Everglide Coral Red",
        "Type": "Linear",
        "ActuationForce": 67,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Amber Orange",
        "CompleteName": "Everglide Amber Orange",
        "Type": "Linear",
        "ActuationForce": 58,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Oreo",
        "CompleteName": "Everglide Oreo",
        "Type": "Tactile",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Tourmaline Blue Cyan",
        "CompleteName": "Everglide Tourmaline Blue Cyan",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 2,
        "BottomOutForce": 55,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Water King V3 55g",
        "CompleteName": "Everglide Water King V3 55g",
        "Type": "Linear",
        "ActuationForce": 40,
        "ActuationDistance": 2,
        "BottomOutForce": 55,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Water King V3 62g",
        "CompleteName": "Everglide Water King V3 62g",
        "Type": "Linear",
        "ActuationForce": 45,
        "ActuationDistance": 2,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Water King V3 67g",
        "CompleteName": "Everglide Water King V3 67g",
        "Type": "Linear",
        "ActuationForce": 55,
        "ActuationDistance": 2,
        "BottomOutForce": 62,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Name": "Dark Jade",
        "CompleteName": "Everglide Dark Jade",
        "Type": "Tactile",
        "ActuationForce": 67,
        "ActuationDistance": 2,
        "BottomOutForce": 67,
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "",
        "Name": "T1 67G",
        "CompleteName": "T1 67G",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": "",
        "BottomOutForce": 67,
        "TravelDistance": "",
        "StemType": "",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "",
        "Name": "T1 65G",
        "CompleteName": "T1 65G",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": "",
        "BottomOutForce": 65,
        "TravelDistance": "",
        "StemType": "",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "",
        "Name": "T1 62G",
        "CompleteName": "T1 62G",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": "",
        "BottomOutForce": 62,
        "TravelDistance": "",
        "StemType": "",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Prime Keyboard",
        "Name": "Alpalca",
        "CompleteName": "Prime Keyboard Alpalca",
        "Type": "Linear",
        "ActuationForce": 62,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Prime Keyboard",
        "Name": "Alpalca V2",
        "CompleteName": "Prime Keyboard Alpalca V2",
        "Type": "Linear",
        "ActuationForce": 62,
        "ActuationDistance": 2,
        "BottomOutForce": "",
        "TravelDistance": 4,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Thickthock",
        "Name": "Marshmallow",
        "CompleteName": "Thickthock Marshmallow",
        "Type": "Linear",
        "ActuationForce": 50,
        "ActuationDistance": 1.4,
        "BottomOutForce": 68,
        "TravelDistance": "",
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gazzew",
        "Name": "Boba U4T 68G",
        "CompleteName": "Gazzew Boba U4T 68G",
        "Type": "Tactle",
        "ActuationForce": "",
        "ActuationDistance": 1.5,
        "BottomOutForce": 68,
        "TravelDistance": 3.7,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gazzew",
        "Name": "Boba U4T 62G",
        "CompleteName": "Gazzew Boba U4T 62G",
        "Type": "Tactle",
        "ActuationForce": "",
        "ActuationDistance": 1.5,
        "BottomOutForce": 62,
        "TravelDistance": 3.7,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gazzew",
        "Name": "Boba U4 62G",
        "CompleteName": "Gazzew Boba U4 62G",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 1.5,
        "BottomOutForce": 62,
        "TravelDistance": 3.7,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "Gazzew",
        "Name": "Boba U4 68G",
        "CompleteName": "Gazzew Boba U4 68G",
        "Type": "Tactile",
        "ActuationForce": "",
        "ActuationDistance": 1.5,
        "BottomOutForce": 68,
        "TravelDistance": 3.7,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    },
    {
        "Brand": "RAMA Works",
        "Name": "Duck",
        "CompleteName": "RAMA Works Duck",
        "Type": "Linear",
        "ActuationForce": 60,
        "ActuationDistance": 1.5,
        "BottomOutForce": 70,
        "TravelDistance": 3.685,
        "StemType": "Cherry",
        "PrebuiltAvailability": "",
        "Notes": ""
    }
]

export const columns = [
    {
      key: "Brand",
      title: "Brand",
      value: (v) => v.Brand,
      sortable: true,
    },
    {
      key: "Name",
      title: "Switch Name",
      value: (v) => v.Name,
      sortable: true,
    },
    {
      key: "Type",
      title: "Type",
      value: (v) => v.Type,
    },
    {
      key: "ActuationForce",
      title: "Actuation (g)",
      value: (v) => v.ActuationForce,
      sortable: true,
    },
    {
      key: "BottomOutForce",
      title: "Bottom Out (g)",
      value: (v) => v.BottomOutForce,
      sortable: true,
    },
    {
      key: "StemType",
      title: "Stem Compatibility",
      value: (v) => v.StemType,
    },
  ]