export const switchData = [
    {
        "Brand": "Cherry",
        "Switch Name": "MX Blue",
        "Switch Name Complete": "Cherry MX Blue",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Black",
        "Switch Name Complete": "Cherry MX Black",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Brown",
        "Switch Name Complete": "Cherry MX Brown",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Red",
        "Switch Name Complete": "Cherry MX Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Clear",
        "Switch Name Complete": "Cherry MX Clear",
        "Type": "Tactile",
        "Actuation Force": 65,
        "Actuation Point": 2,
        "Bottom Out": 95,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Green",
        "Switch Name Complete": "Cherry MX Green",
        "Type": "Clicky",
        "Actuation Force": 70,
        "Actuation Point": 2,
        "Bottom Out": 90,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX White",
        "Switch Name Complete": "Cherry MX White",
        "Type": "Clicky",
        "Actuation Force": 80,
        "Actuation Point": 2.2,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Tactile Grey",
        "Switch Name Complete": "Cherry MX Tactile Grey",
        "Type": "Tactile",
        "Actuation Force": 80,
        "Actuation Point": 2,
        "Bottom Out": 110,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Linear Grey",
        "Switch Name Complete": "Cherry MX Linear Grey",
        "Type": "Linear",
        "Actuation Force": 80,
        "Actuation Point": 2,
        "Bottom Out": 115,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Silent Black",
        "Switch Name Complete": "Cherry MX Silent Black",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 1.9,
        "Bottom Out": 80,
        "Bottom Out Travel": 3.7,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Silver",
        "Switch Name Complete": "Cherry MX Silver",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.2,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Speed Silver",
        "Switch Name Complete": "Cherry MX Speed Silver",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.2,
        "Bottom Out": 65,
        "Bottom Out Travel": 3.4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Silent Red",
        "Switch Name Complete": "Cherry MX Silent Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.9,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.7,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Nature White",
        "Switch Name Complete": "Cherry MX Nature White",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 65,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Low Profile Red",
        "Switch Name Complete": "Cherry MX Low Profile Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.2,
        "Bottom Out": 80,
        "Bottom Out Travel": 3.2,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Cherry",
        "Switch Name": "MX Low Profile Speed",
        "Switch Name Complete": "Cherry MX Low Profile Speed",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1,
        "Bottom Out": 80,
        "Bottom Out Travel": 3.2,
        "Stem Compatibility": "",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Switch Name": "Romer-G Tactile",
        "Switch Name Complete": "Logitech Romer-G Tactile",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 1.5,
        "Bottom Out": 55,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Romer-G",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Switch Name": "Romer-G Linear",
        "Switch Name Complete": "Logitech Romer-G Linear",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.5,
        "Bottom Out": 55,
        "Bottom Out Travel": 3.2,
        "Stem Compatibility": "Romer-G",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Switch Name": "GX Blue",
        "Switch Name Complete": "Logitech GX Blue",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.7,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Switch Name": "GX Brown",
        "Switch Name Complete": "Logitech GX Brown",
        "Type": "Tactile",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Logitech",
        "Switch Name": "GX Red",
        "Switch Name Complete": "Logitech GX Red",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 1.9,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Chery",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Razer",
        "Switch Name": "Green",
        "Switch Name Complete": "Razer Green",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Razer",
        "Switch Name": "Orange",
        "Switch Name Complete": "Razer Orange",
        "Type": "Tactile",
        "Actuation Force": 40,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Razer",
        "Switch Name": "Yellow",
        "Switch Name Complete": "Razer Yellow",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.2,
        "Bottom Out": 45,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Razer",
        "Switch Name": "Clicky Optical Switch",
        "Switch Name Complete": "Razer Clicky Optical Switch",
        "Type": "Clicky",
        "Actuation Force": 45,
        "Actuation Point": 1.5,
        "Bottom Out": 70,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Optical switch"
    },
    {
        "Brand": "Razer",
        "Switch Name": "Linear Optical Switch",
        "Switch Name Complete": "Razer Linear Optical Switch",
        "Type": "Linear",
        "Actuation Force": 40,
        "Actuation Point": 1,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Steelseries",
        "Switch Name": "QS1",
        "Switch Name Complete": "Steelseries QS1",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.5,
        "Bottom Out": 45,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "QS1",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Coolermaster",
        "Switch Name": "Hybrid capacitive",
        "Switch Name Complete": "Coolermaster Hybrid capacitive",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 1,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": "Topre switches"
    },
    {
        "Brand": "Roccat",
        "Switch Name": "Titan",
        "Switch Name Complete": "Roccat Titan",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 1.8,
        "Bottom Out": "",
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": "Only on Roccat boards, force curves to come!"
    },
    {
        "Brand": "IBM",
        "Switch Name": "Buckling Spring",
        "Switch Name Complete": "IBM Buckling Spring",
        "Type": "Clicky",
        "Actuation Force": 70,
        "Actuation Point": 2,
        "Bottom Out": 90,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Buckling Spring",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Topre",
        "Switch Name": 30,
        "Switch Name Complete": "Topre 30",
        "Type": "Tactile",
        "Actuation Force": 30,
        "Actuation Point": 2,
        "Bottom Out": 70,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Topre",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Topre",
        "Switch Name": 35,
        "Switch Name Complete": "Topre 35",
        "Type": "Tactile",
        "Actuation Force": 25,
        "Actuation Point": 2,
        "Bottom Out": 50,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Topre",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Topre",
        "Switch Name": 45,
        "Switch Name Complete": "Topre 45",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Topre",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Topre",
        "Switch Name": 55,
        "Switch Name Complete": "Topre 55",
        "Type": "Tactile",
        "Actuation Force": 65,
        "Actuation Point": 2,
        "Bottom Out": 110,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Topre",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Matias",
        "Switch Name": "Quiet Click",
        "Switch Name Complete": "Matias Quiet Click",
        "Type": "Tactile",
        "Actuation Force": 50,
        "Actuation Point": 2.2,
        "Bottom Out": 35,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "ALPS",
        "Available On Brand Names?": "",
        "Notes": "SKCM/ALPS clones"
    },
    {
        "Brand": "Matias",
        "Switch Name": "Click",
        "Switch Name Complete": "Matias Click",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 2.2,
        "Bottom Out": 35,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "ALPS",
        "Available On Brand Names?": "",
        "Notes": "SKCM/ALPS clones"
    },
    {
        "Brand": "Matias",
        "Switch Name": "Quiet Linear",
        "Switch Name Complete": "Matias Quiet Linear",
        "Type": "Linear",
        "Actuation Force": 35,
        "Actuation Point": 2.2,
        "Bottom Out": 35,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "ALPS",
        "Available On Brand Names?": "",
        "Notes": "SKCM/ALPS clones"
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Clear",
        "Switch Name Complete": "Gateron Clear",
        "Type": "Linear",
        "Actuation Force": 35,
        "Actuation Point": 2.2,
        "Bottom Out": 35,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Not similar to Cherry Clears at all"
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Red",
        "Switch Name Complete": "Gateron Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2.2,
        "Bottom Out": 55,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Yellow",
        "Switch Name Complete": "Gateron Yellow",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Black",
        "Switch Name Complete": "Gateron Black",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": 75,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Brown",
        "Switch Name Complete": "Gateron Brown",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 2.65,
        "Bottom Out": 50,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Blue",
        "Switch Name Complete": "Gateron Blue",
        "Type": "Clicky",
        "Actuation Force": 55,
        "Actuation Point": 2.2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Green",
        "Switch Name Complete": "Gateron Green",
        "Type": "Clicky",
        "Actuation Force": 80,
        "Actuation Point": 2.2,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Ink",
        "Switch Name Complete": "Gateron Ink",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 2.2,
        "Bottom Out": 70,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gateron",
        "Switch Name": "Robin 62G",
        "Switch Name Complete": "Gateron Robin 62G",
        "Type": "Linear",
        "Actuation Force": 40,
        "Actuation Point": 2,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Red",
        "Switch Name Complete": "Kailh Red",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 65,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Brown",
        "Switch Name Complete": "Kailh Brown",
        "Type": "Tactile",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Black",
        "Switch Name Complete": "Kailh Black",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Blue",
        "Switch Name Complete": "Kailh Blue",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Speed Silver",
        "Switch Name Complete": "Kailh Speed Silver",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 1.1,
        "Bottom Out": 70,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Speed Copper",
        "Switch Name Complete": "Kailh Speed Copper",
        "Type": "Tactile",
        "Actuation Force": 50,
        "Actuation Point": 1.1,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Speed Bronze",
        "Switch Name Complete": "Kailh Speed Bronze",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 1.1,
        "Bottom Out": 65,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Speed Pink",
        "Switch Name Complete": "Kailh Speed Pink",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 1.1,
        "Bottom Out": "",
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Speed Gold",
        "Switch Name Complete": "Kailh Speed Gold",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 1.4,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Red",
        "Switch Name Complete": "Kailh Box Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.8,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Black",
        "Switch Name Complete": "Kailh Box Black",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 1.8,
        "Bottom Out": 75,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Navy",
        "Switch Name Complete": "Kailh Box Navy",
        "Type": "Clicky",
        "Actuation Force": 60,
        "Actuation Point": 1.8,
        "Bottom Out": 90,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Jade",
        "Switch Name Complete": "Kailh Box Jade",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 1.8,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Brown",
        "Switch Name Complete": "Kailh Box Brown",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 1.8,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box White",
        "Switch Name Complete": "Kailh Box White",
        "Type": "Clicky",
        "Actuation Force": 45,
        "Actuation Point": 1.8,
        "Bottom Out": 55,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Dark Yellow",
        "Switch Name Complete": "Kailh Box Dark Yellow",
        "Type": "Linear",
        "Actuation Force": 70,
        "Actuation Point": 1.8,
        "Bottom Out": 80,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Pink",
        "Switch Name Complete": "Kailh Box Pink",
        "Type": "Clicky",
        "Actuation Force": 65,
        "Actuation Point": 1.8,
        "Bottom Out": 55,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Chinese Red",
        "Switch Name Complete": "Kailh Box Chinese Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.8,
        "Bottom Out": 55,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Noble Yellow",
        "Switch Name Complete": "Kailh Box Noble Yellow",
        "Type": "Clicky",
        "Actuation Force": 65,
        "Actuation Point": 1.8,
        "Bottom Out": 50,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Glazed Green",
        "Switch Name Complete": "Kailh Box Glazed Green",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 1.8,
        "Bottom Out": 50,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Ancient Grey",
        "Switch Name Complete": "Kailh Ancient Grey",
        "Type": "Linear",
        "Actuation Force": 95,
        "Actuation Point": 1.8,
        "Bottom Out": 100,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Heavy Burnt Orange",
        "Switch Name Complete": "Kailh Heavy Burnt Orange",
        "Type": "Tactile",
        "Actuation Force": 60,
        "Actuation Point": 1.8,
        "Bottom Out": 80,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Royal",
        "Switch Name Complete": "Kailh Box Royal",
        "Type": "Tactile",
        "Actuation Force": 40,
        "Actuation Point": 1.8,
        "Bottom Out": 70,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Pale Blue",
        "Switch Name Complete": "Kailh Box Pale Blue",
        "Type": "Clicky",
        "Actuation Force": 60,
        "Actuation Point": 1.8,
        "Bottom Out": 80,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Pro Burgundy",
        "Switch Name Complete": "Kailh Pro Burgundy",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 1.7,
        "Bottom Out": 70,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Pro Purple",
        "Switch Name Complete": "Kailh Pro Purple",
        "Type": "Tactile",
        "Actuation Force": 50,
        "Actuation Point": 1.7,
        "Bottom Out": 70,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Pro Light Green",
        "Switch Name Complete": "Kailh Pro Light Green",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 1.7,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Low Profile Choc Dark Yellow",
        "Switch Name Complete": "Kailh Low Profile Choc Dark Yellow",
        "Type": "Linear",
        "Actuation Force": 70,
        "Actuation Point": 1.5,
        "Bottom Out": 85,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Kailh Low Profile",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Low Profile Choc Burnt Orange",
        "Switch Name Complete": "Kailh Low Profile Choc Burnt Orange",
        "Type": "Tactile",
        "Actuation Force": 70,
        "Actuation Point": 1.5,
        "Bottom Out": 85,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Kailh Low Profile",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Low Profile Choc Pale Blue",
        "Switch Name Complete": "Kailh Low Profile Choc Pale Blue",
        "Type": "Clciky",
        "Actuation Force": 70,
        "Actuation Point": 1.5,
        "Bottom Out": 85,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Kailh Low Profile",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Low Profile Choc Red",
        "Switch Name Complete": "Kailh Low Profile Choc Red",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 1.5,
        "Bottom Out": 65,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Kailh Low Profile",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Low Profile Choc Brown",
        "Switch Name Complete": "Kailh Low Profile Choc Brown",
        "Type": "Tactile",
        "Actuation Force": 50,
        "Actuation Point": 1.5,
        "Bottom Out": 65,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Kailh Low Profile",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Low Profile Choc White",
        "Switch Name Complete": "Kailh Low Profile Choc White",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 1.5,
        "Bottom Out": 65,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Kailh Low Profile",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Low Profile Choc Navy",
        "Switch Name Complete": "Kailh Low Profile Choc Navy",
        "Type": "Clicky",
        "Actuation Force": 60,
        "Actuation Point": 1.5,
        "Bottom Out": 85,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Kailh Low Profile",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Low Profile Choc Jade",
        "Switch Name Complete": "Kailh Low Profile Choc Jade",
        "Type": "Clicky",
        "Actuation Force": 60,
        "Actuation Point": 1.5,
        "Bottom Out": 75,
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Kailh Low Profile",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Box Red Pro",
        "Switch Name Complete": "Kailh Box Red Pro",
        "Type": "Linear",
        "Actuation Force": 35,
        "Actuation Point": 1.8,
        "Bottom Out": 45,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Kailh",
        "Switch Name": "Speed Navy",
        "Switch Name Complete": "Kailh Speed Navy",
        "Type": "Tactile",
        "Actuation Force": 65,
        "Actuation Point": 1.4,
        "Bottom Out": "",
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Zealios 62 g",
        "Switch Name Complete": "ZealPC Zealios 62 g",
        "Type": "Tactile",
        "Actuation Force": 20,
        "Actuation Point": 2.4,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Zealios 65 g",
        "Switch Name Complete": "ZealPC Zealios 65 g",
        "Type": "Tactile",
        "Actuation Force": 25,
        "Actuation Point": 2.4,
        "Bottom Out": 65,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Zealios 67 g",
        "Switch Name Complete": "ZealPC Zealios 67 g",
        "Type": "Tactile",
        "Actuation Force": 30,
        "Actuation Point": 2.4,
        "Bottom Out": 67,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Zealios 78 g",
        "Switch Name Complete": "ZealPC Zealios 78 g",
        "Type": "Tactile",
        "Actuation Force": 40,
        "Actuation Point": 2.4,
        "Bottom Out": 78,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Lighter Cherry MX Clear, Smoother"
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Tiffany Blue Tealios",
        "Switch Name Complete": "ZealPC Tiffany Blue Tealios",
        "Type": "Linear",
        "Actuation Force": "",
        "Actuation Point": 2.4,
        "Bottom Out": 67,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Orange Healios",
        "Switch Name Complete": "ZealPC Orange Healios",
        "Type": "Linear",
        "Actuation Force": "",
        "Actuation Point": 4,
        "Bottom Out": 67,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Zilents 62 g",
        "Switch Name Complete": "ZealPC Zilents 62 g",
        "Type": "Tactile",
        "Actuation Force": 20,
        "Actuation Point": 2.4,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Silent Zealios"
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Zilents 65 g",
        "Switch Name Complete": "ZealPC Zilents 65 g",
        "Type": "Tactile",
        "Actuation Force": 25,
        "Actuation Point": 2.4,
        "Bottom Out": 65,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Silent Zealios"
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Zilents 67 g",
        "Switch Name Complete": "ZealPC Zilents 67 g",
        "Type": "Tactile",
        "Actuation Force": 30,
        "Actuation Point": 2.4,
        "Bottom Out": 67,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Silent Zealios"
    },
    {
        "Brand": "ZealPC",
        "Switch Name": "Zilents 78 g",
        "Switch Name Complete": "ZealPC Zilents 78 g",
        "Type": "Tactile",
        "Actuation Force": 40,
        "Actuation Point": 2.4,
        "Bottom Out": 78,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Silent Zealios"
    },
    {
        "Brand": "Input Club",
        "Switch Name": "Hako True",
        "Switch Name Complete": "Input Club Hako True",
        "Type": "Tactile",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": 95,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Switch Name": "Hako Clear",
        "Switch Name Complete": "Input Club Hako Clear",
        "Type": "Tactile",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 75,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Switch Name": "Hako Violet",
        "Switch Name Complete": "Input Club Hako Violet",
        "Type": "Tactile",
        "Actuation Force": 40,
        "Actuation Point": 2,
        "Bottom Out": 50,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Switch Name": "Hako Royal True",
        "Switch Name Complete": "Input Club Hako Royal True",
        "Type": "Tactile",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": 85,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Switch Name": "Hako Royal Clear",
        "Switch Name Complete": "Input Club Hako Royal Clear",
        "Type": "Tactile",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 85,
        "Bottom Out Travel": 3.6,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Switch Name": "Halo Clear",
        "Switch Name Complete": "Input Club Halo Clear",
        "Type": "Tactile",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Input Club",
        "Switch Name": "Halo True",
        "Switch Name Complete": "Input Club Halo True",
        "Type": "Tactile",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 100,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Switch Name": "MOD-L",
        "Switch Name Complete": "MOD MOD-L",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Switch Name": "MOD-L",
        "Switch Name Complete": "MOD MOD-L",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Switch Name": "MOD-M",
        "Switch Name Complete": "MOD MOD-M",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Switch Name": "MOD-M",
        "Switch Name Complete": "MOD MOD-M",
        "Type": "Tactile",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 66,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Switch Name": "MOD-H",
        "Switch Name Complete": "MOD MOD-H",
        "Type": "Linear",
        "Actuation Force": 62,
        "Actuation Point": 2,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Switch Name": "MOD-H",
        "Switch Name Complete": "MOD MOD-H",
        "Type": "Tactile",
        "Actuation Force": 62,
        "Actuation Point": 2,
        "Bottom Out": 78,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "MOD",
        "Switch Name": "MOD-SH",
        "Switch Name Complete": "MOD MOD-SH",
        "Type": "Tactile",
        "Actuation Force": 70,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Aliaz",
        "Switch Name": "60g",
        "Switch Name Complete": "Aliaz 60g",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Kind of similar to Zealio"
    },
    {
        "Brand": "Aliaz",
        "Switch Name": "70g",
        "Switch Name Complete": "Aliaz 70g",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 70,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Kind of similar to Zealio"
    },
    {
        "Brand": "Aliaz",
        "Switch Name": "80g",
        "Switch Name Complete": "Aliaz 80g",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Kind of similar to Zealio"
    },
    {
        "Brand": "Aliaz",
        "Switch Name": "100g",
        "Switch Name Complete": "Aliaz 100g",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 100,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": "Kind of similar to Zealio"
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Brown",
        "Switch Name Complete": "Outemu Brown",
        "Type": "Tactile",
        "Actuation Force": 40,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Blue",
        "Switch Name Complete": "Outemu Blue",
        "Type": "Clicky",
        "Actuation Force": 46,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Red",
        "Switch Name Complete": "Outemu Red",
        "Type": "Linear",
        "Actuation Force": 47,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Black",
        "Switch Name Complete": "Outemu Black",
        "Type": "Linear",
        "Actuation Force": 65,
        "Actuation Point": 2,
        "Bottom Out": 84,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Ice Silver",
        "Switch Name Complete": "Outemu Ice Silver",
        "Type": "Linear",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 68,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "ICE Light Purple",
        "Switch Name Complete": "Outemu ICE Light Purple",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "ICE Dustproof Brown",
        "Switch Name Complete": "Outemu ICE Dustproof Brown",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "ICE Dark Purple",
        "Switch Name Complete": "Outemu ICE Dark Purple",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 68,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "ICE Grey",
        "Switch Name Complete": "Outemu ICE Grey",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 75,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "ICE Blue",
        "Switch Name Complete": "Outemu ICE Blue",
        "Type": "Clicky",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "ICE Teal",
        "Switch Name Complete": "Outemu ICE Teal",
        "Type": "Clicky",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 68,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "ICE Click",
        "Switch Name Complete": "Outemu ICE Click",
        "Type": "Clicky",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 75,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Low Profile Red",
        "Switch Name Complete": "Outemu Low Profile Red",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 1.3,
        "Bottom Out": "",
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Low Profile Blue",
        "Switch Name Complete": "Outemu Low Profile Blue",
        "Type": "Clicky",
        "Actuation Force": 60,
        "Actuation Point": 1.3,
        "Bottom Out": "",
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Low Profile Black",
        "Switch Name Complete": "Outemu Low Profile Black",
        "Type": "Linear",
        "Actuation Force": 65,
        "Actuation Point": 1.3,
        "Bottom Out": "",
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Outemu",
        "Switch Name": "Low Profile Brown",
        "Switch Name Complete": "Outemu Low Profile Brown",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 1.3,
        "Bottom Out": "",
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Greetech",
        "Switch Name": "Brown",
        "Switch Name Complete": "Greetech Brown",
        "Type": "Tactile",
        "Actuation Force": 40,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Greetech",
        "Switch Name": "Blue",
        "Switch Name Complete": "Greetech Blue",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Greetech",
        "Switch Name": "Red",
        "Switch Name Complete": "Greetech Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 55,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Greetech",
        "Switch Name": "Black",
        "Switch Name Complete": "Greetech Black",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "Yes",
        "Notes": ""
    },
    {
        "Brand": "Tesoro",
        "Switch Name": "Agile Red",
        "Switch Name Complete": "Tesoro Agile Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 1.5,
        "Bottom Out": "",
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Tesoro",
        "Switch Name": "Agile Blue",
        "Switch Name Complete": "Tesoro Agile Blue",
        "Type": "Clicky",
        "Actuation Force": 45,
        "Actuation Point": 1.5,
        "Bottom Out": "",
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Tesoro",
        "Switch Name": "Slim Blue",
        "Switch Name Complete": "Tesoro Slim Blue",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 1,
        "Bottom Out": "",
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Tesoro",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Tesoro",
        "Switch Name": "Slim Blue",
        "Switch Name Complete": "Tesoro Slim Blue",
        "Type": "",
        "Actuation Force": 45,
        "Actuation Point": 1,
        "Bottom Out": "",
        "Bottom Out Travel": 3,
        "Stem Compatibility": "Tesoro",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Switch Name": "Cream",
        "Switch Name Complete": "NovelKeys Cream",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 70,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Switch Name": "Silk Red",
        "Switch Name Complete": "NovelKeys Silk Red",
        "Type": "Linear",
        "Actuation Force": 35,
        "Actuation Point": 2,
        "Bottom Out": 55,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Switch Name": "Silk Yellow",
        "Switch Name Complete": "NovelKeys Silk Yellow",
        "Type": "Linear",
        "Actuation Force": 43,
        "Actuation Point": 2,
        "Bottom Out": 63.5,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Switch Name": "Silk Black",
        "Switch Name Complete": "NovelKeys Silk Black",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 72,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys",
        "Switch Name": "Silk Olivia",
        "Switch Name Complete": "NovelKeys Silk Olivia",
        "Type": "Linear",
        "Actuation Force": 43,
        "Actuation Point": 2,
        "Bottom Out": 63.5,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Geekmaker",
        "Switch Name": "Creamy Yellow",
        "Switch Name Complete": "Geekmaker Creamy Yellow",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": "",
        "Bottom Out": "",
        "Bottom Out Travel": "",
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Geekmaker",
        "Switch Name": "Creamy Pink",
        "Switch Name Complete": "Geekmaker Creamy Pink",
        "Type": "Linear",
        "Actuation Force": 62,
        "Actuation Point": "",
        "Bottom Out": "",
        "Bottom Out Travel": "",
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Geekmaker",
        "Switch Name": "Creamy Purple",
        "Switch Name Complete": "Geekmaker Creamy Purple",
        "Type": "Linear",
        "Actuation Force": 67,
        "Actuation Point": "",
        "Bottom Out": "",
        "Bottom Out Travel": "",
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Geekmaker",
        "Switch Name": "Creamy Green",
        "Switch Name Complete": "Geekmaker Creamy Green",
        "Type": "Linear",
        "Actuation Force": 78,
        "Actuation Point": "",
        "Bottom Out": "",
        "Bottom Out Travel": "",
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Orange Black",
        "Switch Name Complete": "TTC Orange Black",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Orange Red",
        "Switch Name Complete": "TTC Orange Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Orange Blue",
        "Switch Name Complete": "TTC Orange Blue",
        "Type": "Clicky",
        "Actuation Force": 60,
        "Actuation Point": 2.2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Orange Brown",
        "Switch Name Complete": "TTC Orange Brown",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "YOK",
        "Switch Name": "Red Pandas",
        "Switch Name Complete": "YOK Red Pandas",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": "",
        "Bottom Out": 60,
        "Bottom Out Travel": "",
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "YOK",
        "Switch Name": "Trash Panda",
        "Switch Name Complete": "YOK Trash Panda",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "YOK",
        "Switch Name": "Purple Trash Panda",
        "Switch Name Complete": "YOK Purple Trash Panda",
        "Type": "Tactile",
        "Actuation Force": 57,
        "Actuation Point": 2,
        "Bottom Out": 70,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Silent Red",
        "Switch Name Complete": "TTC Silent Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 55,
        "Bottom Out Travel": 3.8,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Silent Brown",
        "Switch Name Complete": "TTC Silent Brown",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 3.8,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Gold Brown",
        "Switch Name Complete": "TTC Gold Brown",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Gold Pink",
        "Switch Name Complete": "TTC Gold Pink",
        "Type": "",
        "Actuation Force": 37,
        "Actuation Point": 2,
        "Bottom Out": 45,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Wild 42g",
        "Switch Name Complete": "TTC Wild 42g",
        "Type": "Linear",
        "Actuation Force": 42,
        "Actuation Point": 2,
        "Bottom Out": 52,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Wild 55g",
        "Switch Name Complete": "TTC Wild 55g",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 68,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Varmilo",
        "Switch Name": "EC Sakura",
        "Switch Name Complete": "Varmilo EC Sakura",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 60,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Varmilo",
        "Switch Name": "EC Rosery",
        "Switch Name Complete": "Varmilo EC Rosery",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 75,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Varmilo",
        "Switch Name": "EC Ivy",
        "Switch Name Complete": "Varmilo EC Ivy",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 2.3,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "KBT",
        "Switch Name": "Blue",
        "Switch Name Complete": "KBT Blue",
        "Type": "Clicky",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "KBT",
        "Switch Name": "Brown",
        "Switch Name Complete": "KBT Brown",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "KBT",
        "Switch Name": "Red",
        "Switch Name Complete": "KBT Red",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "KBT",
        "Switch Name": "Black",
        "Switch Name Complete": "KBT Black",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Hall Effect",
        "Switch Name": "Linear",
        "Switch Name Complete": "Hall Effect Linear",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": "0.1-3.8",
        "Bottom Out": 65,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Hall Effect",
        "Switch Name": "Clicky",
        "Switch Name Complete": "Hall Effect Clicky",
        "Type": "Clicky",
        "Actuation Force": 60,
        "Actuation Point": "0.1-3.8",
        "Bottom Out": 65,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Hall Effect",
        "Switch Name": "Tactile",
        "Switch Name Complete": "Hall Effect Tactile",
        "Type": "Tactile",
        "Actuation Force": 60,
        "Actuation Point": "0.1-3.8",
        "Bottom Out": 65,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Flaretech",
        "Switch Name": "Red",
        "Switch Name Complete": "Flaretech Red",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": "1.5-3.6",
        "Bottom Out": 55,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Flaretech",
        "Switch Name": "Black",
        "Switch Name Complete": "Flaretech Black",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": "1.5-3.6",
        "Bottom Out": 55,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Flaretech",
        "Switch Name": "Blue",
        "Switch Name Complete": "Flaretech Blue",
        "Type": "Clicky",
        "Actuation Force": 80,
        "Actuation Point": "1.5-3.6",
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "HyperX",
        "Switch Name": "Red",
        "Switch Name Complete": "HyperX Red",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": "",
        "Bottom Out": "",
        "Bottom Out Travel": 3.8,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "HyperX",
        "Switch Name": "Aqua",
        "Switch Name Complete": "HyperX Aqua",
        "Type": "Tactile",
        "Actuation Force": 45,
        "Actuation Point": "",
        "Bottom Out": "",
        "Bottom Out Travel": 3.8,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "c3",
        "Switch Name": "Tangerine",
        "Switch Name Complete": "c3 Tangerine",
        "Type": "Linear",
        "Actuation Force": 62,
        "Actuation Point": "",
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "",
        "Switch Name": "H1s",
        "Switch Name Complete": "H1s",
        "Type": "Linear",
        "Actuation Force": "",
        "Actuation Point": "",
        "Bottom Out": 78,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "TTC",
        "Switch Name": "Gold Pink",
        "Switch Name Complete": "TTC Gold Pink",
        "Type": "Linear",
        "Actuation Force": 37,
        "Actuation Point": 2,
        "Bottom Out": 45,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "NovelKeys x Kailh",
        "Switch Name": "Blueberry",
        "Switch Name Complete": "NovelKeys x Kailh Blueberry",
        "Type": "Tactile",
        "Actuation Force": 55,
        "Actuation Point": 3,
        "Bottom Out": 80,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Drop",
        "Switch Name": "Holy Panda",
        "Switch Name Complete": "Drop Holy Panda",
        "Type": "Tactile",
        "Actuation Force": 44,
        "Actuation Point": 2.4,
        "Bottom Out": 62,
        "Bottom Out Travel": 3.8,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Drop",
        "Switch Name": "Holy Panda X",
        "Switch Name Complete": "Drop Holy Panda X",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2.4,
        "Bottom Out": 62,
        "Bottom Out Travel": 3.5,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Glorious",
        "Switch Name": "Panda",
        "Switch Name Complete": "Glorious Panda",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 2,
        "Bottom Out": 67,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Crystal Violet",
        "Switch Name Complete": "Everglide Crystal Violet",
        "Type": "Tactile",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 63.5,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Sakura Pink",
        "Switch Name Complete": "Everglide Sakura Pink",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Jade Green",
        "Switch Name Complete": "Everglide Jade Green",
        "Type": "Tactile",
        "Actuation Force": 58,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Coral Red",
        "Switch Name Complete": "Everglide Coral Red",
        "Type": "Linear",
        "Actuation Force": 67,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Amber Orange",
        "Switch Name Complete": "Everglide Amber Orange",
        "Type": "Linear",
        "Actuation Force": 58,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Oreo",
        "Switch Name Complete": "Everglide Oreo",
        "Type": "Tactile",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Tourmaline Blue Cyan",
        "Switch Name Complete": "Everglide Tourmaline Blue Cyan",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 2,
        "Bottom Out": 55,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Water King V3 55g",
        "Switch Name Complete": "Everglide Water King V3 55g",
        "Type": "Linear",
        "Actuation Force": 40,
        "Actuation Point": 2,
        "Bottom Out": 55,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Water King V3 62g",
        "Switch Name Complete": "Everglide Water King V3 62g",
        "Type": "Linear",
        "Actuation Force": 45,
        "Actuation Point": 2,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Water King V3 67g",
        "Switch Name Complete": "Everglide Water King V3 67g",
        "Type": "Linear",
        "Actuation Force": 55,
        "Actuation Point": 2,
        "Bottom Out": 62,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Everglide",
        "Switch Name": "Dark Jade",
        "Switch Name Complete": "Everglide Dark Jade",
        "Type": "Tactile",
        "Actuation Force": 67,
        "Actuation Point": 2,
        "Bottom Out": 67,
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "",
        "Switch Name": "T1 67G",
        "Switch Name Complete": "T1 67G",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": "",
        "Bottom Out": 67,
        "Bottom Out Travel": "",
        "Stem Compatibility": "",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "",
        "Switch Name": "T1 65G",
        "Switch Name Complete": "T1 65G",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": "",
        "Bottom Out": 65,
        "Bottom Out Travel": "",
        "Stem Compatibility": "",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "",
        "Switch Name": "T1 62G",
        "Switch Name Complete": "T1 62G",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": "",
        "Bottom Out": 62,
        "Bottom Out Travel": "",
        "Stem Compatibility": "",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Prime Keyboard",
        "Switch Name": "Alpalca",
        "Switch Name Complete": "Prime Keyboard Alpalca",
        "Type": "Linear",
        "Actuation Force": 62,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Prime Keyboard",
        "Switch Name": "Alpalca V2",
        "Switch Name Complete": "Prime Keyboard Alpalca V2",
        "Type": "Linear",
        "Actuation Force": 62,
        "Actuation Point": 2,
        "Bottom Out": "",
        "Bottom Out Travel": 4,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Thickthock",
        "Switch Name": "Marshmallow",
        "Switch Name Complete": "Thickthock Marshmallow",
        "Type": "Linear",
        "Actuation Force": 50,
        "Actuation Point": 1.4,
        "Bottom Out": 68,
        "Bottom Out Travel": "",
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gazzew",
        "Switch Name": "Boba U4T 68G",
        "Switch Name Complete": "Gazzew Boba U4T 68G",
        "Type": "Tactle",
        "Actuation Force": "",
        "Actuation Point": 1.5,
        "Bottom Out": 68,
        "Bottom Out Travel": 3.7,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gazzew",
        "Switch Name": "Boba U4T 62G",
        "Switch Name Complete": "Gazzew Boba U4T 62G",
        "Type": "Tactle",
        "Actuation Force": "",
        "Actuation Point": 1.5,
        "Bottom Out": 62,
        "Bottom Out Travel": 3.7,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gazzew",
        "Switch Name": "Boba U4 62G",
        "Switch Name Complete": "Gazzew Boba U4 62G",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 1.5,
        "Bottom Out": 62,
        "Bottom Out Travel": 3.7,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "Gazzew",
        "Switch Name": "Boba U4 68G",
        "Switch Name Complete": "Gazzew Boba U4 68G",
        "Type": "Tactile",
        "Actuation Force": "",
        "Actuation Point": 1.5,
        "Bottom Out": 68,
        "Bottom Out Travel": 3.7,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    },
    {
        "Brand": "RAMA Works",
        "Switch Name": "Duck",
        "Switch Name Complete": "RAMA Works Duck",
        "Type": "Linear",
        "Actuation Force": 60,
        "Actuation Point": 1.5,
        "Bottom Out": 70,
        "Bottom Out Travel": 3.685,
        "Stem Compatibility": "Cherry",
        "Available On Brand Names?": "",
        "Notes": ""
    }
]